# -*- coding: utf-8 -*-
"""Adding new products.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdJEBWWhi0Ni1qDfC4T8lwToxBudhPq3

**Adding new products**
"""

import json
fd=open("record.json",'r')
r=fd.read()
fd.close()

record=json.loads(r)

product_id=str(input("enter product id:"))
name=str(input("enter product name:"))
pr=int(input("enter the price:"))
qn=int(input("enter the quantity:"))
type=str(input("enter type of product:"))

record[product_id]={"name":name,"qn":qn,"pr":pr,"type":type}

record

"""**Add new item into inventory**"""

product_id=str(input("enter product id:"))
name=str(input("enter product name:"))
pr=int(input("enter the price:"))
qn=int(input("enter the quantity:"))
type=str(input("enter type of product:"))

record[product_id]={"name":name,"qn":qn,"pr":pr,"type":type}



js=json.dumps(record)

fd=open("record.json",'w')
r=fd.write(js)
fd.close()

record